---
title: "Purohitksession6"
author: "kunal"
date: "August 29, 2018"
output: html_document
---
```{r}
data()
```
```{r}
data(cars)
```

```{r}
with(cars, plot(speed, dist))
```
```{r}
with(cars, plot(speed, dist))
title("Speed vs. Stopping distance")
```
```{r}
plot(cars$speed,cars$dist)
title("Speed vs. Stopping distance")
```

```{r}
data(airquality)
#Create the plot/draw canvas
with(airquality, {
        plot(Temp, Ozone)
        lines(loess.smooth(Temp, Ozone))
})
#Add annotation
title("Effect of Ozone on Temperature")
```

```{r}
if(!require(lattice)){install.packages("lattice",repos="http://cran.rstudio.com/")}
```
```{r}
library(lattice)
```

```{r}
state <- data.frame(state.x77, region = state.region)
xyplot(Life.Exp ~ Income | region, data = state, layout = c(4, 1))
```
```{r}
summary(state.x77)
```
print("Hello this is shalin.")

```{r}
library(ggplot2)
#Load built in dataset mpg
data(mpg)
#Create qplot
qplot(displ, hwy, data = mpg)
```

```{r}
data(faithful)
## Make plot appear on screen device
with(faithful, plot(eruptions, waiting))
## Annotate with a title
title(main = "Old Faithful Geyser data")
```
```{r}
## Open PDF device; create 'myplot.pdf' in my working directory
pdf(file = "myplot.pdf")
## Create plot and send to a file (no plot appears on screen)
with(faithful, plot(eruptions, waiting))
## Annotate plot; still nothing on screen
title(main = "Old Faithful Geyser data")
## Close the PDF file device
dev.off()
```

```{r}
with(faithful, plot(eruptions, waiting))
## Add a main title
title(main = "Old Faithful Geyser data")
```

```{r}
dev.copy(png, file = "geyserplot.png")
```

```{r}
dev.off()
```

```{r}
hist(airquality$Ozone)
```

```{r}
airquality <- transform(airquality, Month = factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")
```

```{r}
par("lty")
```

```{r}
par("col")
```

```{r}
par("pch")
```

```{r}
par("bg")
```

```{r}
par("mar")
```

```{r}
par("mfrow")
```

```{r}
with(airquality, plot(Wind, Ozone))
## Add a title
title(main = "Ozone and Wind in New York City")
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City", type = "n"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
with(subset(airquality, Month != 5), points(Wind, Ozone, col = "red"))
legend("topright", pch = 1, col = c("blue", "red"), legend = c("May", "Other Months"))
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City", pch = 20))
## Fit a simple linear regression model
model <- lm(Ozone ~ Wind, airquality)
## Draw regression line on plot
abline(model, lwd = 2)
```

```{r}
par(mfrow = c(1, 2))
with(airquality, {
  plot(Wind, Ozone, main = "Ozone and Wind")
  plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
})
```

```{r}
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
with(airquality, {
  plot(Wind, Ozone, main = "Ozone and Wind")
  plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
  plot(Temp, Ozone, main = "Ozone and Temperature")
  mtext("Ozone and Weather in New York City", outer = TRUE)})
```

```{r}
data("CO2")
#Subset to first 21 observations
CO2=CO2[(1:21),]
#Set R to return to displaying one plot on the screen
par(mfrow=c(1,1))
with(CO2,plot(conc,uptake))
```

```{r}
with(CO2,plot(conc,uptake,col=Plant))
```

```{r}
colors()
```

```{r}
hist(airquality$Ozone, col = "red")
```

```{r}
hist(airquality$Ozone, col = "maroon")
```

```{r}
hist(airquality$Ozone, col = "steelblue")
```

```{r}
with(CO2,plot(conc,uptake,col=rgb(1,0,0)))
```

```{r}
with(CO2,plot(conc,uptake,col=rgb(0,1,0)))
```

```{r}
with(CO2,plot(conc,uptake,col=rgb(0,0,1)))
```

```{r}
with(CO2,plot(conc,uptake,col=rgb(0.4,0,.3)))
```

```{r}
library(RColorBrewer)
```

```{r}
cols <- brewer.pal(3, "BuGn")
cols
```

```{r}
image(volcano,col=cols)
```

```{r}
pal <- colorRampPalette(cols)
pal(20)
```

```{r}
image(volcano, col = pal(20))
```

```{r}
set.seed(1)
x <- rnorm(10000)
y <- rnorm(10000)
smoothScatter(x, y)
```

```{r}
set.seed(2)
x <- rnorm(2000)
y <- rnorm(2000)
plot(x, y, pch = 19)
```

```{r}
plot(x, y, pch = 19, col = rgb(0, 0, 0, 0.15))
```

